version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: jonathan
        uid: 1000
    image: geuser
    container_name: geuser
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    depends_on:
      - redis
      - queue
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    networks:
      - docker-laravel
    depends_on:
      - app


  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9701"
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data:/data
    ports:
      - 9700:9700
      - 9701:9701
    networks:
      - docker-laravel

  pgsql:
    image: postgres:12.17
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: geuser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - docker-laravel

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - docker-laravel

  queue:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: jonathan
        uid: 1000
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www/
    depends_on:
      - redis
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge

volumes:
  pgdata:



  # problemas com o nginx: sudo systemctl stop apache2
